DROP TABLE IF EXISTS statshits;

create TABLE IF NOT EXISTS statshits
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY   NOT NULL,
    app                 VARCHAR(100)                            NOT NULL,
    uri                 VARCHAR(255)                            NOT NULL,
    ip                  VARCHAR(40)                             NOT NULL,
    timestamp           TIMESTAMP  WITHOUT TIME ZONE            NOT NULL
);