create TABLE IF NOT EXISTS users (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL
);

create TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

create TABLE IF NOT EXISTS locations(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

create TABLE IF NOT EXISTS events(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    category_id BIGINT REFERENCES categories (id),
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT REFERENCES users (id) ON delete CASCADE,
    location_id BIGINT REFERENCES locations (id) ON delete CASCADE,
    paid BOOLEAN NOT NULL,
    confirmed_requests BIGINT,
    participant_limit INTEGER DEFAULT 0,
    request_moderation BOOLEAN DEFAULT TRUE,
    state VARCHAR(30) NOT NULL
);

create TABLE IF NOT EXISTS requests(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id BIGINT REFERENCES events (id) ON delete CASCADE,
    requester_id BIGINT REFERENCES users (id) ON delete CASCADE,
    status VARCHAR(55) NOT NULL
);

create TABLE IF NOT EXISTS compilations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN NOT NULL
);

create TABLE IF NOT EXISTS compilations_events(
    compilation_id BIGINT REFERENCES compilations (id) ON delete CASCADE NOT NULL,
    event_id BIGINT REFERENCES events (id) ON delete CASCADE NOT NULL,
    CONSTRAINT compilation_event_pk PRIMARY KEY(compilation_id, event_id)
);

create TABLE IF NOT EXISTS comments(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT REFERENCES users (id) ON delete CASCADE,
    event_id BIGINT REFERENCES events (id) ON delete CASCADE,
    text      VARCHAR(2000) NOT NULL,
    created   TIMESTAMP  WITHOUT TIME ZONE NOT NULL,
    status    VARCHAR(32)  NOT NULL
);